language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: winter.surge.sh
on:
  branch: master
